version: '2.3'

services:
  app:
    image: dan9186/superman
    ports:
      - 4567:4567
    networks:
      - services
    healthcheck:
      test: ["CMD", "/probe", "-kv", "http://localhost:4567/v1/status"]
      interval: 5s
      timeout: 60s
      retries: 3
    env_file: ./env.test

  db:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_USER: superman
      POSTGRES_DB: superman
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    networks:
      services:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superman"]
      interval: 5s
      timeout: 30s
      retries: 3

networks:
  services:
    internal: false
